version: '3.8'

services:
  cardiac-ai-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"      # Frontend (nginx)
      - "8000:8000"  # Backend (FastAPI)
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
